"""initial schema

Revision ID: 6c8175362eee
Revises: 
Create Date: 2026-04-15 22:41:11.896664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c8175362eee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookstore_has_category')
    op.drop_table('bookstore_00')
    op.drop_table('admin')
    op.drop_table('meaning')
    op.drop_table('bookstore_category')
    op.drop_table('word')
    with op.batch_alter_table('admin_voca_book_map', schema=None) as batch_op:
        batch_op.alter_column('voca_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_admin_book_id')
        batch_op.drop_index('ix_admin_voca_id')
        batch_op.drop_index('uq_admin_book_voca')
        batch_op.drop_constraint('fk_admin_map_voca', type_='foreignkey')
        batch_op.drop_constraint('fk_admin_map_book', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin_voca_book', ['book_id'], ['id'])
        batch_op.create_foreign_key(None, 'voca', ['voca_id'], ['id'])

    with op.batch_alter_table('bookstore', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('color',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               nullable=True)
        batch_op.alter_column('hide',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=False,
               existing_server_default=sa.text("'N'"))
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('admin_voca_book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('FK_bookstore_bookstore_category', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('category_id')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('gem_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gem_log_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('fk_gemlog_user', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('goal_type', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=512),
               nullable=True)
        batch_op.alter_column('badge_img',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=128),
               nullable=True)

    with op.batch_alter_table('invite_map', schema=None) as batch_op:
        batch_op.alter_column('inviter_id',
               existing_type=sa.BINARY(length=16),
               comment='초대한 사람 (추천인)',
               existing_nullable=False)
        batch_op.alter_column('invitee_id',
               existing_type=sa.BINARY(length=16),
               comment='초대받은 사람 (피추천인)',
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='상품 고유 ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='스토어 상품 ID (예: com.heyvoca.gems.100)',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='상품명 (예: 보석 100개)',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='상품 설명',
               existing_nullable=True)
        batch_op.alter_column('gem_amount',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='지급할 보석 수량',
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='가격 (원)',
               existing_nullable=False)
        batch_op.alter_column('platform',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='플랫폼 (ios, android)',
               existing_nullable=False)
        batch_op.alter_column('bonus',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='보너스 보석 수량',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('image_url',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='상품 이미지 URL (S3 경로)',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BINARY(length=16),
               comment=None,
               existing_comment='구매 기록 고유 ID (UUID)',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.BINARY(length=16),
               comment=None,
               existing_comment='사용자 ID (외래키)',
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='스토어 상품 ID',
               existing_nullable=False)
        batch_op.alter_column('transaction_id',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='스토어 거래 ID',
               existing_nullable=False)
        batch_op.alter_column('platform',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='플랫폼 (ios, android)',
               existing_nullable=False)
        batch_op.alter_column('gem_amount',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='구매한 보석 수량',
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='구매 가격',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='구매 상태 (completed, refunded, failed)',
               existing_nullable=False,
               existing_server_default=sa.text("'completed'"))
        batch_op.alter_column('receipt_data',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='영수증 원본 데이터 (JSON)',
               existing_nullable=True)
        batch_op.alter_column('verified_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='검증 완료 시간',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('refresh_token',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
        batch_op.drop_index('email')
        batch_op.drop_index('google_id')

    with op.batch_alter_table('user_voca', schema=None) as batch_op:
        batch_op.alter_column('word',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index('ix_user_voca_voca')
        batch_op.drop_constraint('fk_user_voca_voca', type_='foreignkey')
        batch_op.create_foreign_key(None, 'voca', ['voca_id'], ['id'])

    with op.batch_alter_table('user_voca_book', schema=None) as batch_op:
        batch_op.alter_column('voca_list',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_index('vocabook_id')

    with op.batch_alter_table('user_voca_book_map', schema=None) as batch_op:
        batch_op.alter_column('user_voca_book_id',
               existing_type=sa.BINARY(length=16),
               nullable=True)
        batch_op.alter_column('user_voca_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_uvbm_userbook')
        batch_op.drop_index('ix_uvbm_voca')
        batch_op.drop_index('uq_userbook_voca')
        batch_op.drop_constraint('fk_uvbm_userbook', type_='foreignkey')
        batch_op.drop_constraint('FK_user_voca_book_map_user_voca', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_voca', ['user_voca_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_voca_book', ['user_voca_book_id'], ['id'])

    with op.batch_alter_table('voca', schema=None) as batch_op:
        batch_op.drop_index('idx_word')
        batch_op.drop_column('is_active')
        batch_op.drop_column('level')

    with op.batch_alter_table('voca_example', schema=None) as batch_op:
        batch_op.alter_column('exam_en',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('exam_ko',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voca_example', schema=None) as batch_op:
        batch_op.alter_column('exam_ko',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('exam_en',
               existing_type=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('voca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
        batch_op.create_index('idx_word', ['word'], unique=False)

    with op.batch_alter_table('user_voca_book_map', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK_user_voca_book_map_user_voca', 'user_voca', ['user_voca_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_uvbm_userbook', 'user_voca_book', ['user_voca_book_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('uq_userbook_voca', ['user_voca_book_id', 'user_voca_id'], unique=True)
        batch_op.create_index('ix_uvbm_voca', ['user_voca_id'], unique=False)
        batch_op.create_index('ix_uvbm_userbook', ['user_voca_book_id'], unique=False)
        batch_op.alter_column('user_voca_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_voca_book_id',
               existing_type=sa.BINARY(length=16),
               nullable=False)

    with op.batch_alter_table('user_voca_book', schema=None) as batch_op:
        batch_op.create_index('vocabook_id', ['bookstore_id'], unique=False)
        batch_op.alter_column('voca_list',
               existing_type=sa.TEXT(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               existing_nullable=True)

    with op.batch_alter_table('user_voca', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_user_voca_voca', 'voca', ['voca_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_user_voca_voca', ['voca_id'], unique=False)
        batch_op.alter_column('word',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('google_id', ['google_id'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.alter_column('refresh_token',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='수정일시',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('verified_at',
               existing_type=mysql.DATETIME(),
               comment='검증 완료 시간',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('receipt_data',
               existing_type=mysql.TEXT(),
               comment='영수증 원본 데이터 (JSON)',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               comment='구매 상태 (completed, refunded, failed)',
               existing_nullable=False,
               existing_server_default=sa.text("'completed'"))
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               comment='구매 가격',
               existing_nullable=False)
        batch_op.alter_column('gem_amount',
               existing_type=mysql.INTEGER(),
               comment='구매한 보석 수량',
               existing_nullable=False)
        batch_op.alter_column('platform',
               existing_type=mysql.VARCHAR(length=20),
               comment='플랫폼 (ios, android)',
               existing_nullable=False)
        batch_op.alter_column('transaction_id',
               existing_type=mysql.VARCHAR(length=200),
               comment='스토어 거래 ID',
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(length=100),
               comment='스토어 상품 ID',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.BINARY(length=16),
               comment='사용자 ID (외래키)',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BINARY(length=16),
               comment='구매 기록 고유 ID (UUID)',
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='수정일시',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('image_url',
               existing_type=mysql.VARCHAR(length=500),
               comment='상품 이미지 URL (S3 경로)',
               existing_nullable=True)
        batch_op.alter_column('bonus',
               existing_type=mysql.INTEGER(),
               comment='보너스 보석 수량',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('platform',
               existing_type=mysql.VARCHAR(length=20),
               comment='플랫폼 (ios, android)',
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.INTEGER(),
               comment='가격 (원)',
               existing_nullable=False)
        batch_op.alter_column('gem_amount',
               existing_type=mysql.INTEGER(),
               comment='지급할 보석 수량',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=500),
               comment='상품 설명',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               comment='상품명 (예: 보석 100개)',
               existing_nullable=False)
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(length=100),
               comment='스토어 상품 ID (예: com.heyvoca.gems.100)',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='상품 고유 ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('invite_map', schema=None) as batch_op:
        batch_op.alter_column('invitee_id',
               existing_type=sa.BINARY(length=16),
               comment=None,
               existing_comment='초대받은 사람 (피추천인)',
               existing_nullable=False)
        batch_op.alter_column('inviter_id',
               existing_type=sa.BINARY(length=16),
               comment=None,
               existing_comment='초대한 사람 (추천인)',
               existing_nullable=False)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('badge_img',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=128),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=512),
               nullable=False)

    with op.batch_alter_table('goal_type', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('gem_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_gemlog_user', 'user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_gem_log_user_id'))

    with op.batch_alter_table('bookstore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(), server_default=sa.text("'7'"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=False))
        batch_op.create_foreign_key('FK_bookstore_bookstore_category', 'bookstore_category', ['category_id'], ['id'])
        batch_op.alter_column('admin_voca_book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('hide',
               existing_type=sa.String(length=1),
               type_=mysql.CHAR(length=1),
               existing_nullable=False,
               existing_server_default=sa.text("'N'"))
        batch_op.alter_column('color',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               nullable=True,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('admin_voca_book_map', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_admin_map_book', 'admin_voca_book', ['book_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_admin_map_voca', 'voca', ['voca_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('uq_admin_book_voca', ['book_id', 'voca_id'], unique=True)
        batch_op.create_index('ix_admin_voca_id', ['voca_id'], unique=False)
        batch_op.create_index('ix_admin_book_id', ['book_id'], unique=False)
        batch_op.alter_column('book_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('voca_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    op.create_table('word',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('pronunciation', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('example', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bookstore_category',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('meaning',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meaning', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('word_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], name='meaning_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admin',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bookstore_00',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('downloads', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), server_default=sa.text("'N'"), nullable=False),
    sa.Column('color', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), server_default=sa.text("''"), nullable=True),
    sa.Column('hide', mysql.CHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=1), server_default=sa.text("'N'"), nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['voca_book.id'], name='book_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bookstore_has_category',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bookstore_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['bookstore_id'], ['bookstore.id'], name='FK__bookstore'),
    sa.ForeignKeyConstraint(['category_id'], ['bookstore_category.id'], name='FK_bookstore_has_category_bookstore_category'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
