# ─── heyvoca dev ───
server {
    listen 80;
    listen 443 ssl;
    server_name dev-heyvoca-front.ghmate.com;
    ssl_certificate /etc/nginx/certs/cloudflare_chain.crt;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;
    location / {
        proxy_pass http://heyvoca_front_dev:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 86400;
    }
}

server {
    listen 80;
    listen 443 ssl;
    server_name dev-heyvoca-back.ghmate.com;
    ssl_certificate /etc/nginx/certs/cloudflare_chain.crt;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;
    location / {
        proxy_pass http://heyvoca_back_dev:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
    }
}

# ─── heyvoca stg ───
server {
    listen 80;
    listen 443 ssl;
    server_name stg-heyvoca-front.ghmate.com;
    ssl_certificate /etc/nginx/certs/cloudflare_chain.crt;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;
    location / {
        proxy_pass http://heyvoca_front_stg:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    listen 443 ssl;
    server_name stg-heyvoca-back.ghmate.com;
    ssl_certificate /etc/nginx/certs/cloudflare_chain.crt;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;
    location / {
        proxy_pass http://heyvoca_back_stg:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
    }
}

# ─── heyvoca prod ───
server {
    listen 80;
    listen 443 ssl;
    server_name heyvoca-front.ghmate.com;
    ssl_certificate /etc/nginx/certs/cloudflare_chain.crt;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;
    location / {
        proxy_pass http://heyvoca_front_prod:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    listen 443 ssl;
    server_name heyvoca-back.ghmate.com;
    ssl_certificate /etc/nginx/certs/cloudflare_chain.crt;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;
    location / {
        proxy_pass http://heyvoca_back_prod:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
    }
}
