"""initial dict schema

Revision ID: 68edda4a50b7
Revises: 
Create Date: 2026-05-06 10:41:41.103139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68edda4a50b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_voca_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_nm', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    info={'bind_key': 'dict'}
    )
    op.create_table('daily_sentence',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sentence', sa.String(length=200), nullable=False),
    sa.Column('meaning', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('date', 'sentence'),
    info={'bind_key': 'dict'}
    )
    op.create_table('dict_meta',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    info={'bind_key': 'dict'}
    )
    op.create_table('voca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('pronunciation', sa.String(length=100), nullable=True),
    sa.Column('verb_forms', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    info={'bind_key': 'dict'}
    )
    with op.batch_alter_table('voca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voca_word'), ['word'], unique=False)

    op.create_table('voca_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_nm', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    info={'bind_key': 'dict'}
    )
    op.create_table('voca_example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_en', sa.Text(), nullable=True),
    sa.Column('exam_ko', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    info={'bind_key': 'dict'}
    )
    op.create_table('voca_meaning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meaning', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    info={'bind_key': 'dict'}
    )
    op.create_table('admin_voca_book_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voca_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('voca_meanings', sa.TEXT(), nullable=True),
    sa.Column('voca_examples', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['admin_voca_book.id'], ),
    sa.ForeignKeyConstraint(['voca_id'], ['voca.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'bind_key': 'dict'}
    )
    op.create_table('bookstore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('gem', sa.Integer(), nullable=False),
    sa.Column('hide', sa.String(length=1), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('admin_voca_book_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_voca_book_id'], ['admin_voca_book.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['voca_book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    info={'bind_key': 'dict'}
    )
    op.create_table('voca_book_map',
    sa.Column('voca_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['voca_book.id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voca_id'], ['voca.id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voca_id', 'book_id'),
    info={'bind_key': 'dict'}
    )
    op.create_table('voca_example_map',
    sa.Column('voca_id', sa.Integer(), nullable=False),
    sa.Column('example_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['example_id'], ['voca_example.id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voca_id'], ['voca.id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voca_id', 'example_id'),
    info={'bind_key': 'dict'}
    )
    op.create_table('voca_meaning_map',
    sa.Column('voca_id', sa.Integer(), nullable=False),
    sa.Column('meaning_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meaning_id'], ['voca_meaning.id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voca_id'], ['voca.id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voca_id', 'meaning_id'),
    info={'bind_key': 'dict'}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voca_meaning_map')
    op.drop_table('voca_example_map')
    op.drop_table('voca_book_map')
    op.drop_table('bookstore')
    op.drop_table('admin_voca_book_map')
    op.drop_table('voca_meaning')
    op.drop_table('voca_example')
    op.drop_table('voca_book')
    with op.batch_alter_table('voca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voca_word'))

    op.drop_table('voca')
    op.drop_table('dict_meta')
    op.drop_table('daily_sentence')
    op.drop_table('admin_voca_book')
    # ### end Alembic commands ###
