"""voca_meaning_concept N:M 매핑 테이블 추가

Revision ID: 6efb3b1f9711
Revises: d4a85c7f910e
Create Date: 2026-09-21 08:53:24.651095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efb3b1f9711'
down_revision = 'd4a85c7f910e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voca_meaning_concept',
    sa.Column('meaning_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meaning_id'], ['voca_meaning.id'], onupdate='NO ACTION', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meaning_id', 'concept_id'),
    info={'bind_key': 'dict'}
    )
    with op.batch_alter_table('voca_meaning_concept', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voca_meaning_concept_concept_id'), ['concept_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voca_meaning_concept', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voca_meaning_concept_concept_id'))

    op.drop_table('voca_meaning_concept')
    # ### end Alembic commands ###
