"""voca_example_meta 예문 메타 테이블 추가

Revision ID: 9a3613020398
Revises: fb145745a70c
Create Date: 2026-09-30 03:54:49.793564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a3613020398'
down_revision = 'fb145745a70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voca_example_meta',
    sa.Column('example_id', sa.Integer(), autoincrement=False, nullable=False, comment='voca_example.id 참조(FK 없음 — 파생 테이블, 규칙상 명시 FK 생략)'),
    sa.Column('level', mysql.TINYINT(), nullable=False, comment='1 초급 / 2 중급 / 3 상급'),
    sa.Column('word_count', mysql.SMALLINT(), nullable=False, comment='태그 제거 영어 평문 단어 수'),
    sa.Column('rare_count', mysql.SMALLINT(), nullable=False, comment='목표 단어를 뺀 내용어 중 빈도 낮은(zipf < 3.5 또는 미상) 단어 수'),
    sa.Column('words', sa.JSON(), nullable=False, comment='목표 단어 구간과 기능어를 뺀 내용어의 원형(소문자) 리스트 — "아는 단어" 비율 계산용'),
    sa.Column('source', sa.String(length=32), nullable=False, comment='dict(기존) / gen20260930(이번 생성) 등 생성 배치 표식'),
    sa.PrimaryKeyConstraint('example_id'),
    info={'bind_key': 'dict'}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voca_example_meta')
    # ### end Alembic commands ###
