"""voca_example_puzzle 예문 조각 조립 문제 테이블 추가

Revision ID: e7acdea50898
Revises: 6efb3b1f9711
Create Date: 2026-09-28 01:50:49.236108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7acdea50898'
down_revision = '6efb3b1f9711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voca_example_puzzle',
    sa.Column('example_id', sa.Integer(), autoincrement=False, nullable=False, comment='voca_example.id 참조(FK 없음 — 파생 테이블, 규칙상 명시 FK 생략)'),
    sa.Column('sentence_hash', sa.String(length=64), nullable=False, comment='정규화(태그 제거·소문자·문장부호 제거·공백 1개)한 영어 평문의 sha256 — 사용자 단어장에 복사된 예문을 문장 텍스트로 매칭하기 위함'),
    sa.Column('tokens', sa.JSON(), nullable=False, comment='문장부호를 뺀 조각 리스트, 원문 어순'),
    sa.Column('target_idx', sa.JSON(), nullable=False, comment='목표 단어에 해당하는 tokens 인덱스 리스트'),
    sa.Column('first_form', sa.String(length=64), nullable=True, comment='tokens[0]의 문장 중간 표기(소문자화 등) — 조각 뱅크 표시용'),
    sa.Column('alt_orders', sa.JSON(), nullable=True, comment='허용 어순 리스트 — 각 원소는 tokens와 같은 길이의 재배열(조각 리스트)'),
    sa.Column('distractors', sa.JSON(), nullable=True, comment='의미 방해 조각 리스트 (sentenceArrange* 오답 보기용)'),
    sa.Column('listen_distractors', sa.JSON(), nullable=True, comment='소리 방해 조각 리스트 (listenArrange 오답 보기용)'),
    sa.Column('skip_reason', sa.String(length=64), nullable=True, comment='있으면 이 example은 조립형 4종 출제 후보에서 제외'),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('example_id'),
    info={'bind_key': 'dict'}
    )
    with op.batch_alter_table('voca_example_puzzle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voca_example_puzzle_sentence_hash'), ['sentence_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voca_example_puzzle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voca_example_puzzle_sentence_hash'))

    op.drop_table('voca_example_puzzle')
    # ### end Alembic commands ###
