"""bookstore level 컬럼 제거

Revision ID: e88a423260ff
Revises: fb357e514820
Create Date: 2026-07-20 21:55:18.824001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e88a423260ff'
down_revision = 'fb357e514820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookstore', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookstore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=True))

    # ### end Alembic commands ###
