"""add admin_voca_book_map_meaning/example ref tables

Revision ID: fb145745a70c
Revises: e7acdea50898
Create Date: 2026-09-28 18:13:54.825105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb145745a70c'
down_revision = 'e7acdea50898'
branch_labels = None
depends_on = None


def _has_table(name):
    return sa.inspect(op.get_bind()).has_table(name)


def upgrade():
    # 이미 있으면 건너뛴다(2026-09-29). 일본어 사전(heyvoca_dict_ja)은 alembic 이 아니라
    # 사전 dump(apply_version)로 이 두 테이블을 받는데, dump 의 alembic_version 은 이 리비전
    # 이전이라 부팅 시 ja 마이그레이션이 CREATE TABLE 을 다시 시도해 1050 으로 부팅이 멈췄다.
    if not _has_table('admin_voca_book_map_example'):
        _create_example()
    if not _has_table('admin_voca_book_map_meaning'):
        _create_meaning()


def _create_example():
    op.create_table('admin_voca_book_map_example',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('example_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['example_id'], ['voca_example.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_id'], ['admin_voca_book_map.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id', 'example_id'),
    info={'bind_key': 'dict'}
    )


def _create_meaning():
    op.create_table('admin_voca_book_map_meaning',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('meaning_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['admin_voca_book_map.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meaning_id'], ['voca_meaning.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id', 'meaning_id'),
    info={'bind_key': 'dict'}
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_voca_book_map_meaning')
    op.drop_table('admin_voca_book_map_example')
    # ### end Alembic commands ###
