"""add admin_voca_book_map_meaning/example ref tables

Revision ID: fb145745a70c
Revises: e7acdea50898
Create Date: 2026-09-28 18:13:54.825105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb145745a70c'
down_revision = 'e7acdea50898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_voca_book_map_example',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('example_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['example_id'], ['voca_example.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_id'], ['admin_voca_book_map.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id', 'example_id'),
    info={'bind_key': 'dict'}
    )
    op.create_table('admin_voca_book_map_meaning',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('meaning_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['admin_voca_book_map.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meaning_id'], ['voca_meaning.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id', 'meaning_id'),
    info={'bind_key': 'dict'}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_voca_book_map_meaning')
    op.drop_table('admin_voca_book_map_example')
    # ### end Alembic commands ###
