"""add voca_label

Revision ID: fb357e514820
Revises: b020d4838dde
Create Date: 2026-07-13 21:24:33.475907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb357e514820'
down_revision = 'b020d4838dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voca_label',
    sa.Column('voca_id', sa.Integer(), nullable=False),
    sa.Column('cefr', sa.String(length=2), nullable=True),
    sa.Column('cefr_source', sa.String(length=16), nullable=True),
    sa.Column('freq_zipf', sa.Float(), nullable=True),
    sa.Column('pos', sa.String(length=16), nullable=True),
    sa.Column('pos_wordnet', sa.String(length=16), nullable=True),
    sa.Column('lemma', sa.String(length=255), nullable=True),
    sa.Column('sense_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['voca_id'], ['voca.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voca_id'),
    info={'bind_key': 'dict'}
    )
    with op.batch_alter_table('voca_label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voca_label_cefr'), ['cefr'], unique=False)
        batch_op.create_index(batch_op.f('ix_voca_label_freq_zipf'), ['freq_zipf'], unique=False)
        batch_op.create_index(batch_op.f('ix_voca_label_lemma'), ['lemma'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voca_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voca_label_lemma'))
        batch_op.drop_index(batch_op.f('ix_voca_label_freq_zipf'))
        batch_op.drop_index(batch_op.f('ix_voca_label_cefr'))

    op.drop_table('voca_label')
    # ### end Alembic commands ###
