FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

ARG VITE_BACKEND_URL
ARG VITE_DEBUG=false
ARG NODE_ENV=staging
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_DEBUG=$VITE_DEBUG
ENV NODE_ENV=$NODE_ENV

COPY . .
RUN npm run build       # Vite가 ENV를 읽어 dist 생성

FROM nginx:1.27-alpine
COPY nginx.stg.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]