version: '3.8'

services:
  web:
    container_name: heyvoca_back_dev
    image: whrksp126/heyvoca_back:dev
    build: 
      context: .
      dockerfile: Dockerfile
      platforms: 
        - linux/amd64
    ports:
      - "5002:5000"
    env_file:
      - .env.dev
    networks:
      - heyvoca_back_dev_network

networks:
  heyvoca_back_dev_network:
    name: heyvoca_back_dev_network
